### ISSUE TITLE
deep.html test doesn't work in safari (sometimes)

### ISSUE THREAD

**Issue by joozek78** [Palindrom/palindrom-polymer-client#24]
See [travis build](https://travis-ci.org/PuppetJs/puppet-polymer-client/builds/133938089) - it fails around 50% of cases. Currently test is disabled on safari

**Comment by joozek78** [comment]
cc @warpech @miyconst please take a look on this - you have macs

**Comment by warpech** [comment]
This was not a problem since many months. Archiving
