### ISSUE TITLE
onLocalChange won't work with other changes than 'replace'

### ISSUE THREAD

**Issue by joozek78** [Palindrom/palindrom-polymer-client#26]
While working on fix for puppetjs/puppetjs#85 `onLocalChange` has been changed to notify Polymer about changes, but not provide info on removed elements (which is required by Polymer when notifying about array splices). This works fine currently, because we only ever generate 'replace' operations, but it could result in bugs in future.

This could probably be solved by returning results from `jsonpatch.generate` similar to `jsonpatch.apply`

**Comment by warpech** [comment]
Archiving. We will fix this when this becomes a problem.
