### ISSUE TITLE
When there is a connection error, show the request that caused it

### ISSUE THREAD

**Issue by warpech** [Palindrom/palindrom-polymer-client#31]
When there is a connection error, show the request that caused it.

If the request was HTTP, show the relevant HTTP information:
- request method
- request URL
- request & response headers
- request & response body

If the request was WebSocket, show the relevant information:
- last patch message body

**Comment by alshakero** [comment]
This is all done in https://github.com/Palindrom/palindrom-polymer-client/pull/55

**Comment by warpech** [comment]
Closing as done
