### ISSUE TITLE
notifySplices fails with proxified arrays

### ISSUE THREAD

**Issue by alshakero** [Palindrom/palindrom-polymer-client#40]
Proxified arrays in object tree can't be notified. I isolated everything and this is my conclusion for now.

Method:

I made two separate folders:
1.  One that depends on Palindrom with Proxies which is failing **all** array tests.
2.  One that uses the old Puppet with dirty checking. 

I polyserved both and compared values through every step of the execution using Chrome debugger, I couldn't spot any difference in values in `notifyTemplateDomBind` function. The only difference is proxification. To be able to compare I did this:

```js
case 'replace':
    var originalObjString = JSON.stringify(templateDomBind.get('model'));
    var parentString = JSON.stringify(parent);
    /* I copied both values from proxies-version and normal version and compared them */
    debugger;
    templateDomBind.notifySplices(parentsPolymerPath,
        [{
            index: parseInt(name, 10),
            removed: [result],
            addedCount: 1,
            object: parent,
            type: 'splice'
        }]
    );
    break;
```

Both instances, the proxy-powered, and the old one have exactly the same values. I compared with `===` to make sure. So I can safely say that Palindrom is updating the tree correctly, the splice object is correct, but Polymer is failing to be notified about the proxified arrays. 

To try you can checkout `proxies-version` branch and compare values. 

@warpech @tomalec

**Comment by warpech** [comment]
Did you try to step in to `notifySplices` and check at what line it acts differently for proxy and dirty-checking? It is complex, but synchronous, so it should be possible to track.

**Comment by alshakero** [comment]
@warpech Oh I spent most of the time doing this. In polymer.html, there is a function called `_applySplicesArrayOrder`

It has this code: 
```js
_applySplicesArrayOrder: function (splices) {
            for (var i = 0, s; i < splices.length && (s = splices[i]); i++) {
                for (var j = 0; j < s.removed.length; j++) {
                    this._detachAndRemoveInstance(s.index);
                }
                for (j = 0; j < s.addedKeys.length; j++) {
                    this._insertPlaceholder(s.index + j, s.addedKeys[j]);
                }
            }
        },
```
And it loops through the splices we pass in our function `notifyTemplateDomBind`, exactly here:
```js
templateDomBind.notifySplices(parentsPolymerPath,
    [{
        index: parseInt(name, 10),
        removed: [result],
        addedCount: 1,
        object: parent,
        type: 'splice'
    }]
);
```

But as you can see in the first loop, it expects an array called `addedKeys` to exist, and this array should be added dynamically by Polymer. But it's failing to do so.

To understand this array, I debugged the working version, and it's an array of keys prefixed with a `#`, so I monkey-added it our splices. Even though the error disappeared, it isn't working still.

**Comment by warpech** [comment]
Let's reverse the problem. Could you use some standalone Polymer demo that takes an array a property (maybe https://www.webcomponents.org/element/PolymerElements/iron-list) and see if that works with a proxified array? If it does not, that's something to report in the Polymer issue tracker.

**Comment by alshakero** [comment]
@warpech great idea. Going for it.

**Comment by alshakero** [comment]
A little report.

I think I pinpointed the issue. And it's in Palindrom not in `palindrom-client`. Tomorrow I'll implement a solution.

`onRemoteChange` is being called before `onDataReady`. And it is being called with the non-proxified object. And this renders the following code in `palindrom-client` useless:
```
callback: function (obj) {
    this.set('obj', obj);
    if (whereToBind) {
        this.bindTo(whereToBind);
    }
}.bind(this)
```
Because `onPatchApplied` is being called on an empty `model` object.

We need to make some architectural changes in Palindrom API.

**Comment by alshakero** [comment]
Closing as fixed.
