### ISSUE TITLE
Version 3.x: ignoreAdd was set to /.+/ all add operations on root were dismissed

### ISSUE THREAD

**Issue by alshakero** [Palindrom/palindrom-polymer-client#42]
It seems to me that before, we had `ignoreAdd` default set to `/.+/`. And this means ignore all `add` operations on the root level. I did test that, and true, anything you added to the root of `palindrom.obj` was ignored (not synced with the server) without any configuration. 

This issue is to explain and document this behaviour for people who will face it (99% will happen), now that `ignoreAdd` is removed. Because apparently, `ignoreAdd` affects everyone, not only people who used it.

Now with `palindrom-client` 4.0.0, this issue arises when your view model (PageName.json) is missing one or more properties. And you try to set values to these properties from the client side. You'll get a console error and connection will break. Whereas with 3.x, these failed silently and went unnoticed. 

If you migrated to 4.0.0 and need to fix this, you need to pre-add all the properties you will set to `Palindrom.obj` to the view model. And this error will be fixed, see [this KitchenSink commit](https://github.com/StarcounterApps/KitchenSink/commit/38660048329fc52e6400c35fa127ab922811f388
) for an example.

I have several doubts about my conclusions, please correct me if anything is wrong with this @tomalec @warpech.

**Comment by tomalec** [comment]
> This issue arises when your view model (PageName.json) is missing one or more properties. And you try to set values to these properties from the client side. You'll get a console error and connection will break.

Isn't it the correct behavior?

**Comment by alshakero** [comment]
Yes, this is the correct behaviour. But not the real-life behaviour with 3.x. `palindrom-client` ignored all root additions and the no errors happened.

**Comment by alshakero** [comment]
@tomalec but you're right, my explanation was misleading. I edited it.

**Comment by warpech** [comment]
This is what I meant here https://github.com/Palindrom/Palindrom/issues/136#issuecomment-309871900 and we decided that was not a problem. If this becomes a problem, just make sure that the JavaScript error in the console gives you a clue what is wrong.

What was the symptom of https://github.com/StarcounterApps/KitchenSink/pull/149? Any nice error message, or totally misleading?

**Comment by alshakero** [comment]
Misleading. I had to use `sc-debug-aid` and compare the object tree before and after the error to see the extra property.

![image](https://user-images.githubusercontent.com/17054134/27871654-9d46cd9e-61a6-11e7-96d7-1cc691bfa8dc.png)

(First warning is not ours).

**Comment by warpech** [comment]
I will make sure the error reported in the Chrome console includes the stack trace.

**Comment by warpech** [comment]
Archiving. This is now explained in [Starcounter's changelog](https://github.com/Starcounter/level1/blob/v2.3/CHANGELOG.md) (ctrl+f "ignoreadd") and [Palindrom 3.0.0 release notes](https://github.com/Palindrom/Palindrom/releases/tag/v3.0.0)
