### ISSUE TITLE
Rename to `palindrom-connection`

### ISSUE THREAD

**Issue by alshakero** [Palindrom/palindrom-polymer-client#43]
This element will be renamed to `palindrom-connection`. It will instantiate a PalindromDOM instance, initiate a connection and emit all PalindromDOM events (encapsulates JS callbacks and dispatches DOM events around them).

Middleware between this element and frameworks will be called `palindrom-frameworkname` like `palindrom-polymer`.

**Comment by warpech** [comment]
Was this issue completely abandoned or temporarily skipped? I am putting this to "Freezer" but if it was abandoned, it should be closed.

**Comment by warpech** [comment]
Archiving, as this first has to be discussed globally in https://github.com/Starcounter/RebelsLounge/issues/217
